#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Terminate already running polybar, eww, picom, sxhkd and dunst instances
#processes=("picom" "polybar" "eww" "sxhkd" "dunst")

#for process in "${processes[@]}"; do
#  if pidof -q "$process"; then
    #pkill -9 -x "$process" > /dev/null; sleep 0.1
#  fi
#done

#Auto Start application
sxhkd &
picom --config "$HOME"/.config/picom/picom.conf &
nitrogen --restore &
#polybar &
~/.config/polybar/simple.sh &
dunst -conf "$HOME"/.config/dunst/dunstrc &


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
